backend:
  name: git-gateway
  branch: main

site_url: https://michiana.dev
display_url: https://michiana.dev

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "SEO Title (under 55 characters)", name: "seoTitle", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Hero Image", name: "heroImage", widget: "image", required: false }
      - { label: "Hero Image Alt Text", name: "heroImageAlt", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
